name: Test & Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 12.x
          
      - name: Set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'
          channel: 'stable'
      
      - name: Flutter version
        run: flutter --version
          
      - name: Set up test environment
        run: flutter pub get
        
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/allokate_keystore.jks'
          encodedString: ${{ secrets.ENCODED_KEYSTORE }}
    
#      - run: echo "${{ secrets.ENCODED_KEYSTORE }}" | base64 --decode > android/app/key.jks
                        
#        - run: flutter format --set-exit-if-changed .
        
        #   run static analys code
#        - run: flutter analyze
            
      - name: Build APK (Android)
        run: flutter build appbundle
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD}}
          
          
      - uses: actions/upload-artifact@v1
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
